### ISSUE TITLE
BUG - Gulp task `vf-css:package-info` fails on Windows

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#635]
One to sort when back from the conference, probably a Windows path matching issue. 

``` 
[04:45:05] Starting 'vf-component-assets:directory'...                                        
[04:45:05] Starting 'vf-component-assets:compiled-css'...                                    
 [04:45:05] 'vf-css:package-info' errored after 68 ms                                          
[04:45:05] TypeError: Cannot read property 'forEach' of undefined                             
    at C:\Users\khawk\Documents\GitHub\vf-eleventy\node_modules\@visual-framework\vf-core\tools\gulp-tasks\vf-css.js:93:13                                                               
       at C:\Users\khawk\Documents\GitHub\vf-eleventy\node_modules\@visual-framework\vf-core\tools\css-generator\recursive-readdir.js:47:18                                               
         at FSReqCallback.oncomplete (fs.js:158:21)                                               
 [04:45:05] 'vf-css' errored after 80 ms                                                      
 [04:45:05] 'build' errored after 156 ms                                                      
 [04:45:05] The following tasks did not complete: vf-scripts, vf-component-assets, vf-scripts:es5, vf-component-assets:directory, vf-component-assets:compiled-css                        
```
Spotted when running `vf-eleventy`.

**Comment by khawkins98** [comment]
This was due to a code snippet that resulted in a busted symlink at  https://visual-framework.github.io/vf-welcome/troubleshooting/

Fixed by https://github.com/visual-framework/vf-welcome/commit/72001ade6bad9ef08d1aa64243e96be37e4dfca2
